@startuml
'https://plantuml.com/class-diagram

class Packaging {
Packaging : -Material
Packaging : +canFitItem()
Packaging : +getMass()
}

class Box {
Box : -length : BigDecimal
Box : -width : BigDecimal
Box : -height : BigDecimal
}

class PolyBag {
PolyBag : -volume : BigDecimal
}

enum Material {
Material : CORRUGATE
Material : LAMINATED_PLASTIC
}

Packaging <|-- Box
Packaging <|-- PolyBag
Packaging o-- Material

@enduml